version: '2'
services:
  tnt-app:
    image: tnt
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tnt-postgresql:5432/tnt
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://tnt-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://tnt-elasticsearch:9200
    ports:
      - 8080:8080
  tnt-postgresql:
    extends:
      file: postgresql.yml
      service: tnt-postgresql
  tnt-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: tnt-elasticsearch
